package com.drools.training;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer age;
	private java.lang.String name;
	private java.lang.Integer income;
	private java.lang.String creditCardApproval;

	public Person() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getIncome() {
		return this.income;
	}

	public void setIncome(java.lang.Integer income) {
		this.income = income;
	}

	public java.lang.String getCreditCardApproval() {
		return this.creditCardApproval;
	}

	public void setCreditCardApproval(java.lang.String creditCardApproval) {
		this.creditCardApproval = creditCardApproval;
	}

	public Person(java.lang.Integer age, java.lang.String name,
			java.lang.Integer income, java.lang.String creditCardApproval) {
		this.age = age;
		this.name = name;
		this.income = income;
		this.creditCardApproval = creditCardApproval;
	}

}